### ISSUE TITLE
Error while running bin/magento setup:di:compile

### ISSUE THREAD

**Issue by clivewalkden** [bentideswell/magento2-wordpress-integration#1]
Getting the following when running setup:di:compile on the server.

```
The deploy has failed with an error: Exception while executing as x.com@1.2.3.4: magento exit status: 255
magento stdout: Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 38.0 MiBPHP Fatal error:  Uncaught Error: Undefined constant 'FishPig\WordPress\Helper' in /var/www/vhosts/x.com/deployments/releases/20160609161401/magento/app/code/FishPig/WordPress/Helper/Plugin.php:9
Stack trace:
#0 /var/www/vhosts/x.com/deployments/releases/20160609161401/magento/vendor/composer/ClassLoader.php(412): include()
#1 /var/www/vhosts/x.com/deployments/releases/20160609161401/magento/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/vhosts...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('FishPig\\WordPre...')
#3 [internal function]: spl_autoload_call('FishPig\\WordPre...')
#4 /var/www/vhosts/x.com/deployments/releases/20160609161401/magento/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(69): class_exists('\\FishPig\\WordPr...')
#5 /var/www/vhosts/x.com/deployments/releases/20160609161401/magento/setup/src/Magento/Setup/Module/Di/ in /var/www/vhosts/x.com/deployments/releases/20160609161401/magento/app/code/FishPig/WordPress/Helper/Plugin.php on line 9
magento stderr: Nothing written
```

**Comment by bentideswell** [comment]
Hi Clive,

Thank you for posting the first bug/issue to this GitHub!

This issue should now be fixed via the commit 6bd588ba1f92fc23b1ad63cad7e67c4e4be3228a.

I'll leave this open so if you can confirm that it's fixed for you, I will then close the issue.

**Comment by clivewalkden** [comment]
I'll give it a go shortly, thanks for fixing so quick!

**Comment by clivewalkden** [comment]
Checked and it is fixed. I did have to set the memory limit for PHP to 1G. Ran with the following command
`php -d memory_limit=1G -f bin/magento setup:di:compile`

**Comment by bentideswell** [comment]
Thanks for the feedback. I also had to do that but set the memory limit to -1, allowing it to use as much memory as it needed.

php -d memory_limit=-1 -f bin/magento setup:di:compile
