### ISSUE TITLE
Error when generating sitemap

### ISSUE THREAD

**Issue by adamj88** [bentideswell/magento2-wordpress-integration#113]
When generating the sitemap we're receiving the following error:

```
TypeError: Return value of FishPig\WordPress\Model\Sitemap\ItemProvider\Post::getPostImages() must be of the type array, object returned in /vendor/fishpig/magento2-wordpress-integration/Model/Sitemap/ItemProvider/Post.php
```

Removing the array type from the following method appears to resolve it: https://github.com/bentideswell/magento2-wordpress-integration/blob/master/Model/Sitemap/ItemProvider/Post.php#L54 - but is this the best way to do it?

Full stack trace:

```
[2021-08-17 10:53:47] .CRITICAL: TypeError: Return value of FishPig\WordPress\Model\Sitemap\ItemProvider\Post::getPostImages() must be of the type array, object returned in /vendor/fishpig/magento2-wordpress-integration/Model/Sitemap/ItemProvider/Post.php:68
Stack trace:
#0 /vendor/fishpig/magento2-wordpress-integration/Model/Sitemap/ItemProvider/Post.php(38): FishPig\WordPress\Model\Sitemap\ItemProvider\Post->getPostImages()
#1 /vendor/fishpig/magento2-wordpress-integration/Model/Sitemap/ItemProvider/AbstractItemProvider.php(78): FishPig\WordPress\Model\Sitemap\ItemProvider\Post->_getItems()
#2 /vendor/magento/module-sitemap/Model/ItemProvider/Composite.php(36): FishPig\WordPress\Model\Sitemap\ItemProvider\AbstractItemProvider->getItems()
#3 /vendor/magento/module-sitemap/Model/Sitemap.php(366): Magento\Sitemap\Model\ItemProvider\Composite->getItems()
#4 /vendor/mageworx/module-xmlsitemap/Model/OtherSitemapItemsAdapter.php(21): Magento\Sitemap\Model\Sitemap->_initSitemapItems()
#5 /vendor/mageworx/module-xmlsitemap/Model/Generator/Other.php(58): MageWorx\XmlSitemap\Model\OtherSitemapItemsAdapter->getItems()
#6 /vendor/mageworx/module-xmlsitemap/Model/GeneratorManager.php(162): MageWorx\XmlSitemap\Model\Generator\Other->generate()
#7 /vendor/mageworx/module-xmlsitemap/Model/Sitemap.php(154): MageWorx\XmlSitemap\Model\GeneratorManager->generateXml()
#8 /vendor/mageworx/module-xmlsitemap/Controller/Adminhtml/Sitemap/Generate.php(30): MageWorx\XmlSitemap\Model\Sitemap->generateXml()
#9 /vendor/magento/framework/Interception/Interceptor.php(58): MageWorx\XmlSitemap\Controller\Adminhtml\Sitemap\Generate->execute()
#10 /vendor/magento/framework/Interception/Interceptor.php(138): MageWorx\XmlSitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor->___callParent()
#11 /vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): MageWorx\XmlSitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor->Magento\Framework\Interception\{closure}()
#12 /vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute()
#13 /vendor/magento/framework/Interception/Interceptor.php(153): MageWorx\XmlSitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor->Magento\Framework\Interception\{closure}()
#14 /generated/code/MageWorx/XmlSitemap/Controller/Adminhtml/Sitemap/Generate/Interceptor.php(23): MageWorx\XmlSitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor->___callPlugins()
#15 /vendor/magento/framework/App/Action/Action.php(111): MageWorx\XmlSitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor->execute()
#16 /vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#17 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#18 /vendor/magento/framework/Interception/Interceptor.php(138): MageWorx\XmlSitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor->___callParent()
#19 /vendor/weltpixel/m2-weltpixel-backend/Plugin/Utility.php(76): MageWorx\XmlSitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor->Magento\Framework\Interception\{closure}()
#20 /vendor/magento/framework/Interception/Interceptor.php(135): WeltPixel\Backend\Plugin\Utility->aroundDispatch()
#21 /vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): MageWorx\XmlSitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor->Magento\Framework\Interception\{closure}()
#22 /vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#23 /vendor/magento/framework/Interception/Interceptor.php(153): MageWorx\XmlSitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor->Magento\Framework\Interception\{closure}()
#24 /generated/code/MageWorx/XmlSitemap/Controller/Adminhtml/Sitemap/Generate/Interceptor.php(32): MageWorx\XmlSitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor->___callPlugins()
#25 /vendor/magento/framework/App/FrontController.php(186): MageWorx\XmlSitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor->dispatch()
#26 /vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest()
#27 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#28 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#29 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#30 /generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#31 /vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#32 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#33 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent()
#34 /vendor/justbetter/magento2-sentry/Plugin/GlobalExceptionCatcher.php(58): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#35 /vendor/magento/framework/Interception/Interceptor.php(135): JustBetter\Sentry\Plugin\GlobalExceptionCatcher->aroundLaunch()
#36 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#37 /generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins()
#38 /vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch()
#39 /pub/index.php(31): Magento\Framework\App\Bootstrap->run()
#40 {main} [] []
```

**Comment by bentideswell** [comment]
Hi @adamj88, removing the array return type is the correct fix. I have released an upgrade which implements this.
