### ISSUE TITLE
Updated to 2.0.0.5 cannot view blog page

### ISSUE THREAD

**Issue by Kershrew** [bentideswell/magento2-wordpress-integration#77]
When visiting the main blog page I now get this message:
```
Fatal error: Uncaught Error: Call to undefined method FishPig\WordPress\Model\ResourceModel\Term::getFactory() in /home/hervia/public_html/vendor/bentideswell/magento2-wordpress-integration/Model/ResourceModel/Term/Collection.php:199 Stack trace: #0 /home/hervia/public_html/vendor/bentideswell/magento2-wordpress-integration/Block/Sidebar/Widget/Cloud.php(28): FishPig\WordPress\Model\ResourceModel\Term\Collection->addCloudFilter('post_tag') #1 [internal function]: FishPig\WordPress\Block\Sidebar\Widget\Cloud->getTags() #2 /home/hervia/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(82): call_user_func_array(Array, Array) #3 /home/hervia/public_html/app/design/frontend/Mtc/hervia/FishPig_WordPress/templates/sidebar/widget/cloud.phtml(9): Magento\Framework\View\TemplateEngine\Php->__call('getTags', Array) #4 /home/hervia/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/hervia/pu...') #5 /home/hervia/public_html/vendor/magento/framework/View/Element/Template.php(270): Magen in /home/hervia/public_html/vendor/bentideswell/magento2-wordpress-integration/Model/ResourceModel/Term/Collection.php on line 199
```

Work around:
Add `return false;` to start of `getTags()` function which is declared on line 18 of `\Block\Siderbar\Widget\Cloud.php`:
```
public function getTags()
{
	return false;
	if ($this->hasTags()) {
		return $this->_getData('tags');
	}
	
	$this->setTags(false);
	
	$tags = $this->factory->create('Model\ResourceModel\Term\Collection')
		->addCloudFilter($this->getTaxonomy())
		->setOrderByName()
		->load();

	if (count($tags) > 0) {
		$max = 0;
		$hasPosts = false;
		
		foreach($tags as $tag) {
			$max = $tag->getCount() > $max ? $tag->getCount() : $max;
			
			if ($tag->getCount() > 0) {
				$hasPosts = true;
			}
		}
		
		if ($hasPosts) {
			$this->setMaximumPopularity($max);
			$this->setTags($tags);
		}
	}

	return $this->getData('tags');
}
```

**Comment by bentideswell** [comment]
2.0.0.6 has been released that fixes this issue.
